<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF Builder - PDFGate</title>
    <style>
        body { margin: 0; font-family: Arial, Helvetica, sans-serif; background: #f5f5f5; color: #111; }
        .page { max-width: 960px; margin: 0 auto; padding: 32px; }
        .card { background: #fff; border-radius: 16px; padding: 24px; box-shadow: 0 18px 40px rgba(0,0,0,0.08); }
        .field { margin-bottom: 20px; }
        label { display: block; margin-bottom: 8px; font-weight: 600; }
        input[type=text], textarea { width: 100%; border: 1px solid #d1d5db; border-radius: 12px; padding: 12px; font-size: 1rem; }
        textarea { min-height: 180px; resize: vertical; }
        button { border: none; border-radius: 12px; background: #2563eb; color: white; font-weight: 700; padding: 14px 20px; cursor: pointer; }
        button:disabled { opacity: 0.6; cursor: not-allowed; }
        .row { display: flex; gap: 20px; flex-wrap: wrap; }
        .row > * { flex: 1; }
        .notice { margin-top: 16px; padding: 14px 16px; border-radius: 12px; background: #eef2ff; color: #3730a3; }
        .download-link { display: inline-block; margin-top: 16px; color: #2563eb; text-decoration: none; font-weight: 700; }
        iframe { width: 100%; height: 650px; border: 1px solid #d1d5db; border-radius: 16px; margin-top: 28px; }
        .header { display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:16px; margin-bottom:24px; }
        .back-link { color:#2563eb; text-decoration:none; font-weight:700; }
    </style>
</head>
<body>
    <div class="page">
        <div class="header">
            <div>
                <h1 style="margin:0 0 8px;">PDF Builder</h1>
                <p style="margin:0; color:#4b5563;">Create a PDF instantly from title and body text.</p>
            </div>
            <a href="{{ route('dashboard') }}" class="back-link">Back to Dashboard</a>
        </div>

        <div class="card">
            <div class="field">
                <label for="title">Document Title</label>
                <input id="title" type="text" placeholder="My first PDF" value="Sample PDF Title" />
            </div>

            <div class="field">
                <label for="body">Document Body</label>
                <textarea id="body" placeholder="Paste the PDF body text here">This is a sample PDF generated by PDFGate.\n\nEdit the title or body and click Generate PDF.</textarea>
            </div>

            <div class="row">
                <button id="generate">Generate PDF</button>
            </div>

            <div class="notice">
                You are generating PDF documents as <strong>{{ auth()->user()->email }}</strong>. All usage is tracked in your account.
            </div>

            <a id="downloadLink" href="#" class="download-link" style="display:none;">Open generated PDF in a new tab</a>

            <iframe id="previewFrame" style="display:none;"></iframe>
        </div>
    </div>

    <script>
        const generateButton = document.getElementById('generate');
        const titleInput = document.getElementById('title');
        const bodyInput = document.getElementById('body');
        const previewFrame = document.getElementById('previewFrame');
        const downloadLink = document.getElementById('downloadLink');

        function setLoading(loading) {
            generateButton.disabled = loading;
            generateButton.textContent = loading ? 'Generating...' : 'Generate PDF';
        }

        generateButton.addEventListener('click', async () => {
            const title = titleInput.value.trim();
            const body = bodyInput.value.trim();

            if (!title || !body) {
                alert('Please fill in both title and body.');
                return;
            }

            setLoading(true);
            downloadLink.style.display = 'none';
            previewFrame.style.display = 'none';

            try {
                const response = await fetch('/pdf-builder', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-TOKEN': '{{ csrf_token() }}',
                    },
                    body: JSON.stringify({ title, body }),
                });

                if (!response.ok) {
                    const payload = await response.json().catch(() => null);
                    const message = payload?.message || payload?.errors || response.statusText;
                    throw new Error(message || 'Failed to generate PDF');
                }

                const blob = await response.blob();
                const url = URL.createObjectURL(blob);
                previewFrame.src = url;
                previewFrame.style.display = 'block';

                downloadLink.href = url;
                downloadLink.textContent = 'Open generated PDF in a new tab';
                downloadLink.style.display = 'inline-block';
            } catch (error) {
                alert(error.message || 'Unable to generate PDF.');
            } finally {
                setLoading(false);
            }
        });
    </script>
</body>
</html>
