<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; margin: 36px; }
        h1 { font-size: 24px; margin-bottom: 16px; }
        p { font-size: 14px; line-height: 1.6; }
        .footer { margin-top: 32px; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <h1>{{ $title }}</h1>
    <div>{!! nl2br(e($body)) !!}</div>
    <div class="footer">Generated by PDFGate</div>
</body>
</html>
